before_script:
  - echo "Before script"
  - cd /var/www/apusds_dev/
building:
  stage: build
  script:
    - git reset --hard
    - git pull origin master
    - composer install --no-ansi --no-interaction
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
deploying:
  stage: deploy
  script:
    - echo "Deployed"
